{{ if .Values.use_ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
spec:
  rules:
  - host: {{.Values.hostname}}.{{.Values.domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: monitoring-grafana
          servicePort: http
{{ end }}
