{{ if .Values.use_ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: kube-system
spec:
  rules:
  - host: {{.Values.hostname}}.{{.Values.domain}}
    http:
      paths:
      - backend:
          serviceName: monitoring-grafana
          servicePort: 80
{{ end }}
