---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      task: {{ template "name" . }}-task
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        task: {{ template "name" . }}-task
        version: v0.0.1
        release: {{ .Release.Name }}
    spec:
      containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
            - containerPort: {{ .Values.service.internalPort }}
            resources:
{{ toYaml .Values.resources | indent 15 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
 